name: Demo1
on:
  push:
    branches:
    - 'release'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  call-workflow1:
    uses: ./.github/workflows/workflow1.yaml
  call-workflow2:
    if: ${{ always()}}
    needs: call-workflow1
    uses: ./.github/workflows/workflow2.yaml
