name: deploy to heroku
on:
  push:
    branches:
    - 'release'
    
jobs:
  job1:
    name: angular build
    build:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: 'project_frontend'
      steps:
      - name: Checkout Angular code
        uses: actions/checkout@v2
      - name: Setup node-version
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: NPM Install
        run: npm install --legacy-peer-deps
      - name: NPM install Angular
        run: npm install -g --legacy-peer-deps @angular/cli > /dev/null
      - name: NPM build
        run: npm run build
      - name: Remove existing DIST files in server (if any)
        run: rm -rf ../FPServer/src/main/resources/static/*
      - name: Copying files to server
        run : cp -r './dist/fpangular/' '../FPServer/src/main/resources/static'
  job2:
    name: spring build
    needs: job1
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v2
    - name: deploy to heroku 
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: leslie-survey
        heroku_email: "leslielowgy@gmail.com"
        appdir: "project_backend"

    