name: Deploy to heroku
on:
  push:
    branches:
    - 'release'
jobs:
  deploy_to_heroku:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'project_backend'
    steps: 
     - name: Checkout
       uses: actions/checkout@v2
     - name: deploy to heroku 
       uses: akhileshns/heroku-deploy@v3.12.12
       with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: leslie-survey
          heroku_email: "leslielowgy@gmail.com"
          appdir: "project_backend"
